setup ui test framework
S2U2MLancer/show-me-blog pull request #24
Opened 2019-06-16 05:51 UTC by gyfpython

resolve #23

2019-06-17 00:21 UTC, xiayy860612 requested changes
rm all binay files, you can add a script to intall some dependences.

2019-06-17 00:21 UTC, xiayy860612 commented on test/Smoking_test_suite/utils/logfuction.py
> +        #实例化TimedRotatingFileHandler
rm unusage code, if any help knowledge, put into wiki.

2019-06-17 00:22 UTC, xiayy860612 requested changes

2019-06-17 00:22 UTC, xiayy860612 commented on test/Smoking_test_suite/testcases/testtitle.py
> +        self.driver = webdriver.Chrome('../resources/chromedriver.exe')
how about linux?

2019-06-18 00:48 UTC, xiayy860612 requested changes
merge all changes into one commit:

- git fetch
- git rebase -i orgin dev, in edit first one should be `p`, others use `s` for each commit
- git push -f

2019-06-18 00:48 UTC, xiayy860612 commented on test/Smoking_test_suite/utils/downloaddriver.py
> +        download("http://npm.taobao.org/mirrors/chromedriver/73.0.3683.68/chromedriver_win32.zip")
can we use pip install this chromedriver?
refer to https://pypi.org/project/chromedriver-binary/

2019-06-18 00:48 UTC, xiayy860612 commented on test/Smoking_test_suite/requirement.txt
> +requests
you'd better add version for requests library.

2019-06-18 00:48 UTC, xiayy860612 commented on test/Smoking_test_suite/utils/downloaddriver.py
> +def download(downloadurl):
it seems an private method, you'd better add prefix `__`  for method name

2019-06-19 13:34 UTC, gyfpython commented
git rebase 4 commit to 1/requests version added/prefix __ for private method name

2019-06-21 00:59 UTC, xiayy860612 approved these changes

2019-06-21 00:59 UTC, merged